/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.ListCellRenderer;
import javax.swing.table.TableCellRenderer;
import sk.stu.fiit.Loader;
import sk.stu.fiit.Project;
import sk.stu.fiit.Team;
import sk.stu.fiit.User;

/**
 *
 * @author patoh
 */
public class AllProjectsSummary extends javax.swing.JFrame {

    /**
     * Creates new form AllProjectsSummary
     */
    private User user;
    private static final Logger LOG = Logger.getLogger(AllProjectsSummary.class.getName());
    
    /**
     * Konstruktor triedy AllProjectSummary
     * @param user Pouzivatel, ktoreho projekty sa zobrazia
     */
    public AllProjectsSummary(User user) {
        this.user = user;
        initComponents();
        setProjectValues();
        
        if(user.getType().equals("project_manager") ||  user.getType().equals("admin"))
            btnAddTask.setVisible(true);
        else
            btnAddTask.setVisible(false);
        
    }
    
    /**
     * Konstruktor triedy AllProjectSummary. Zobrazia sa vsetky vytvorene
     * projekty.
     */
    public AllProjectsSummary(){
        user = null;
        initComponents();
        setProjectValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPName = new javax.swing.JLabel();
        lblPid = new javax.swing.JLabel();
        lblPDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        btnAddTask = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Project Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Project ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Deadline");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jLabel3, gridBagConstraints);

        lblPName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblPName.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(lblPName, gridBagConstraints);

        lblPid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblPid.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(lblPid, gridBagConstraints);

        lblPDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblPDate.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(lblPDate, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Assigned to");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jLabel8, gridBagConstraints);

        userList.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        userList.setForeground(new java.awt.Color(0, 0, 0));
        userList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(userList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        description.setEditable(false);
        description.setColumns(20);
        description.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        description.setLineWrap(true);
        description.setRows(5);
        description.setWrapStyleWord(true);
        jScrollPane3.setViewportView(description);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jScrollPane3, gridBagConstraints);

        btnAddTask.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAddTask.setText("Add task");
        btnAddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTaskMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(btnAddTask, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        projectList.setFixedCellHeight(100);
        projectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        projectList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                projectListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(projectList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Pri zatvarani okna sa ulozi aktualny rozmer do suboru XML.
     * @param evt 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Loader.saveDimension(this.getClass().getName(), this.getSize());
    }//GEN-LAST:event_formWindowClosing

    /**
     * Funkcia zabezpeci zobrazenie okna takej velkosti, aka je ulozena v XML
     * subore.
     * @param evt 
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
            this.setPreferredSize(Loader.lookupDimension(this.getClass().getName()));
            pack();
        }catch(Exception ex){
            LOG.log(Level.SEVERE, "Chyba pri citani rozmerov z XML suboru");
        }
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * Pri zmene vyberu projekt zo zoznamu funkcia zabezpeci aktualizovanie
     * udajov zvolenej polozky (Project) zo zoznamu
     * @param evt 
     */
    private void projectListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_projectListValueChanged
        
        if(!projectList.isSelectionEmpty()){
            Project selected = projectList.getSelectedValue();
            setProjectValues(selected);
        }
    }//GEN-LAST:event_projectListValueChanged

    /**
     * Funkcia spracovava stlacenie tlacidla pre pridelovanie novej ulohy k
     * existujucemu projektu.
     * @param evt 
     */
    private void btnAddTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTaskMouseClicked
        if(!projectList.isSelectionEmpty()){
            Project selected = projectList.getSelectedValue();
            if(selected != null){
                JFrame newTask = new NewTask(selected);
                newTask.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnAddTaskMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllProjectsSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllProjectsSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllProjectsSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllProjectsSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllProjectsSummary().setVisible(true);
            }
        });
    }

    /**
     * Funkica nastavi hodnoty detailu projektu podla zvolenej polozky
     * @param project Projekt, ktoreho detail sa ma zobrazit.
     */
    private void setProjectValues(Project project){
        if(project != null){
            lblPDate.setText(new SimpleDateFormat("dd.MM.yyyy").format(project.getDeadline()));
            lblPName.setText(project.getProjectName());
            lblPid.setText(project.getId());
            description.setText(project.getDescription());
            DefaultListModel<User> model=  new DefaultListModel<>();
            
            project.getTeams().forEach(team -> {
                team.getTeamMembers().forEach(member -> {
                    model.addElement(member);
                });
            });
            userList.setModel(model);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPDate;
    private javax.swing.JLabel lblPName;
    private javax.swing.JLabel lblPid;
    private javax.swing.JList<Project> projectList;
    private javax.swing.JList<User> userList;
    // End of variables declaration//GEN-END:variables

  
    
    
  /**
   * Funkcia zabezpeci inicializovanie hodnot v liste s projektmi.
   */  
  private void setProjectValues(){

     DefaultListModel model  = new DefaultListModel();
        
        projectList.setCellRenderer(new MyCellRenderer());
        
        Loader.getProjects().values().forEach(project ->{
            if(user == null ||
                    (user.getType().equals("project_manager") && project.getProject_manager().getUsername().equals(user.getUsername())) ||
                    user.getType().equals("admin") ||
                         project.hasUser(user)){
                
                    model.addElement(project);
        
            }
        });
        
        projectList.setModel(model);
    }

}

class ProjectDetailTableCellRender implements TableCellRenderer{

   
    private User user;
    
    /**
     * Konstruktor pre render bunky v tabulke zobrazujucej detail projektu.
     * @param user Pouzivatel, ktoreho projekty sa zobrazuju
     */
    public ProjectDetailTableCellRender(User user){
        this.user = user;
    }
    
    /**
     * Konstruktor pre render bunky v tabulke zobrazujucej detail projektu.
     */
    public ProjectDetailTableCellRender(){
        user = null;
    }
    
    /**
     * Funkcia inicializuje hodnoty v bunke tabulky zaznamenavajucej
     * detaily projektu.
     * @param table Tabulka, na ktoru sa aplikuje CellRender
     * @param value Hodnota vlozena do bunky tabulky
     * @param isSelected Hodnota zaznamenavajuca, ci pouzivatel klikol na bunku
     * @param hasFocus Hodnota zaznamenavajuca ci ma bunka focus
     * @param row Index zvoleneho riadku
     * @param column Index zvoleneho stlpca
     * @return JPanel s inicializovanymi udajmi o projekte podla value
     */
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        
        JPanel projectDetail = new ProjectTableItem((Project) value);
        
        if(isSelected){
            table.setForeground(table.getSelectionForeground());
            table.setBackground(table.getSelectionBackground());
            projectDetail.setForeground(Color.red);
            projectDetail.setBackground(Color.BLUE);
        }else {
          table.setForeground(table.getForeground());
          table.setBackground(table.getBackground());
          projectDetail.setForeground(table.getForeground());
          projectDetail.setBackground(new Color(204,204,255));
        }
        
        return projectDetail;
        
    }
    
      
    
}


 class MyCellRenderer extends JPanel implements ListCellRenderer<Object> {
     public MyCellRenderer() {
        // setOpaque(true);
     }

    /**
     * Funkcia zaznamen
     * @param list
     * @param value
     * @param index
     * @param isSelected
     * @param cellHasFocus
     * @return 
     */
    @Override
    public Component getListCellRendererComponent(JList<? extends Object> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        JPanel projectDetail = new ProjectTableItem((Project) value);
        
        if(isSelected){
            list.setForeground(list.getSelectionForeground());
            list.setBackground(list.getSelectionBackground());
            projectDetail.setForeground(Color.red);
            projectDetail.setBackground(Color.BLUE);
        }else {
          list.setForeground(list.getForeground());
          list.setBackground(list.getBackground());
          projectDetail.setForeground(list.getForeground());
          projectDetail.setBackground(new Color(204,204,255));
        }
        
        return projectDetail;
    }

     
}
