/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sk.stu.fiit.InputVerifiers;
import sk.stu.fiit.Loader;
import sk.stu.fiit.User;

/**
 *  Trieda, ktorej ulohou je zabezpecit vytvorenie noveho pouzivatela.
 * @author Patrik Heglas
 */
public class NewUserFactory extends javax.swing.JFrame {

   
    private  String filepath = null;
    private static final Logger LOG = Logger.getLogger(NewUserFactory.class.getName());
    /**
     * Konstruktor, v ktorom sa inicializuju komponenty okna
     */
    public NewUserFactory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        btnCreateUser = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ageSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        statusCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        photoLbl = new javax.swing.JLabel();
        addPictureBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(498, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnCreateUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnCreateUser.setText("Create Profile");
        btnCreateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateUserMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel1.add(btnCreateUser, gridBagConstraints);

        nameField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(nameField, gridBagConstraints);

        addressField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(addressField, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Age");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel1.add(jLabel3, gridBagConstraints);

        ageSpinner.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(16, 16, 80, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(ageSpinner, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel5, gridBagConstraints);

        passwordField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(passwordField, gridBagConstraints);

        statusCombo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "admin", "user", "director" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(statusCombo, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel6, gridBagConstraints);

        usernameField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(usernameField, gridBagConstraints);

        photoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLbl.setText("No profile picture");
        photoLbl.setMaximumSize(new java.awt.Dimension(200, 200));
        photoLbl.setMinimumSize(new java.awt.Dimension(100, 100));
        photoLbl.setPreferredSize(new java.awt.Dimension(150, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(photoLbl, gridBagConstraints);

        addPictureBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addPictureBtn.setText("Profile Picture");
        addPictureBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPictureBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel1.add(addPictureBtn, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Pridanie fotky k pouzivatelovi.
     * @param evt 
     */
    private void addPictureBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPictureBtnMouseClicked
         final JFileChooser fc = new JFileChooser();
          fc.setCurrentDirectory(new File(".")); //NOI18N
        int desc = fc.showOpenDialog(fc);
     
       
        
        if(desc == JFileChooser.APPROVE_OPTION){
            filepath = fc.getSelectedFile().getAbsolutePath();
            File file = new File(filepath);
            String relative  = new File(".").toURI().relativize(new File(filepath).toURI()).getPath(); //NOI18N
            
            if (!InputVerifiers.check_image(file)){
                JOptionPane.showMessageDialog(rootPane, "Chosen file is not an image!", "Wrong file", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ImageIcon photo = new ImageIcon(filepath);
            
            if(photo != null){
            
            BufferedImage bi=new BufferedImage(photoLbl.getWidth(),photoLbl.getHeight(), BufferedImage.TYPE_INT_RGB);

            Graphics2D g = bi.createGraphics();
            Image image = photo.getImage();
            g.drawImage(image, 0, 0, photoLbl.getWidth(),photoLbl.getHeight(), null);

            g.dispose();
            
            photoLbl.setText(null);
            
            photoLbl.setIcon(new ImageIcon(bi));
        }
            
        }
        
        
    }//GEN-LAST:event_addPictureBtnMouseClicked

    /**
     * Funkcia zabezpecuje pridavanie noveho pouzivatela do systemu.
     */
    private void btnCreateUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateUserMouseClicked
        try{
            InputVerifiers.hasEmptyFields(nameField, usernameField, passwordField,
                    addressField);

            User newUser = null;

            String status = ((String) statusCombo.getSelectedItem()).trim();
            int age = (int) ageSpinner.getValue();



            if(!status.isEmpty()){
               newUser = new User(usernameField.getText(), String.valueOf(passwordField.getPassword()),
                       nameField.getText(), age, addressField.getText(), status, filepath);
            }

            if(newUser != null)
              Loader.addUser(newUser);

            this.dispose();

        }catch(RuntimeException ex){
            LOG.log(Level.SEVERE, ex.getMessage());
        }
    }//GEN-LAST:event_btnCreateUserMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPictureBtn;
    private javax.swing.JTextField addressField;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
