/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import sk.stu.fiit.Loader;
import sk.stu.fiit.Priorities;
import sk.stu.fiit.Project;
import sk.stu.fiit.Tasks.Task;
import sk.stu.fiit.Team;
import sk.stu.fiit.User;

/**
 *  Trieda ovadajuca JPanel zobrazujuci tedal o priradenych pracovnikov
 * k projektu
 * @author Patrik Heglas
 */
public class ProjectTeammates extends javax.swing.JPanel {

    
    
    private Project project;
    private List<User> users;
    
    /**
     * Konstruktor, ktory inicializuje komponenty v okne
     * @param project Projekt, podla ktoreho sa inicializuju komponenty
     */
    public ProjectTeammates(Project project) {
        this.project = project;
        users = new ArrayList<>();
        
        if(project != null)
            addUserToTable(project.getProject_manager());
        
        initComponents();
        setValues();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        projectPriorityGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        teammateTable = new javax.swing.JTable();
        userCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnAddTask = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Project > Teammates", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/bundle"); // NOI18N
        jLabel1.setText(bundle.getString("TEAMMATES")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(jLabel1, gridBagConstraints);

        lblName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText(bundle.getString("JLABEL2")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        add(lblName, gridBagConstraints);

        lblDescription.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(0, 0, 0));
        lblDescription.setText(bundle.getString("JLABEL3")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        add(lblDescription, gridBagConstraints);

        btnAddUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAddUser.setText(bundle.getString("ADD USER")); // NOI18N
        btnAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUserMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(btnAddUser, gridBagConstraints);

        teammateTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        teammateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teammateTable.setColumnSelectionAllowed(true);
        teammateTable.setDragEnabled(true);
        teammateTable.setRowHeight(36);
        teammateTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(teammateTable);
        teammateTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(jScrollPane1, gridBagConstraints);

        userCombo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        userCombo.setInheritsPopupMenu(true);
        userCombo.setMinimumSize(new java.awt.Dimension(250, 29));
        userCombo.setPreferredSize(new java.awt.Dimension(250, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(userCombo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(jLabel4, gridBagConstraints);

        btnAddTask.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAddTask.setText(bundle.getString("ADD TASK")); // NOI18N
        btnAddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTaskMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(btnAddTask, gridBagConstraints);

        btnContinue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnContinue.setText(bundle.getString("CONTINUE")); // NOI18N
        btnContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinueMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(btnContinue, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Po kliknuti na tlacidlo zobrazi okno pre pridanie ulohy.
     * @param evt 
     */
    private void btnAddTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTaskMouseClicked
        JFrame taskFrame = new NewTask(project);
        taskFrame.setVisible(true);
    }//GEN-LAST:event_btnAddTaskMouseClicked

    /**
     * Po kliknuti na tlacidlo pokracuje na konecne zobrazenie informacii o
     * vytvaranom projekte.
     * @param evt 
     */
    private void btnContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseClicked
        users.add(project.getProject_manager());
        
        if(users.size() > 0){
             project.add(new Team(users, java.util.ResourceBundle.getBundle("sk/stu/fiit/bundle").getString("CORE TEAM")));
         }
         
        JPanel next = new ProjectSummary(project);
            Container pane = this.getParent();
            
            pane.removeAll();
            next.setVisible(true);
            pane.add(next);
            pane.revalidate();
            pane.repaint();
    }//GEN-LAST:event_btnContinueMouseClicked

    /**
     * Po kliknuti na tlacidlo priradi pouzivatela k projektu.
     * @param evt 
     */
    private void btnAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserMouseClicked
        User selected = (User) userCombo.getSelectedItem();
        if(selected != null){
            users.add(selected);
            addUserToTable(selected);
        }
        
    }//GEN-LAST:event_btnAddUserMouseClicked

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.ButtonGroup projectPriorityGroup;
    private javax.swing.JTable teammateTable;
    private javax.swing.JComboBox<User> userCombo;
    // End of variables declaration//GEN-END:variables

    /**
     * Funkcia sluzi pre nastavenie hodnot komponentov v JPanel
     * podla aktualne vytvaraneho projektu.
     */
    private void setValues(){
        lblName.setText(project.getProjectName());
        lblDescription.setText(project.getDescription());
        
        Loader.getUsers().forEach(user ->{
            userCombo.addItem(user);
        });
        
    }
    
    /**
     * Funkcia sluzi na vyvorenie zaznamu v tabulke s priradenymi pouzivatelmi.
     * @param user Pouzivatel, ktoreho informacie sa vkladaju do tabulky.
     */
    private void addUserToTable(User user){
        if(user != null){
            DefaultTableModel model =  (DefaultTableModel) teammateTable.getModel();
            model.addRow(new Object[]{user.getName(), user.getUsername(), user.getType() });
        }
    }
    
}
