/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import sk.stu.fiit.Loader;
import sk.stu.fiit.Project;
import sk.stu.fiit.Tasks.Task;
import sk.stu.fiit.Team;
import sk.stu.fiit.User;

/**
 * Trieda, v ktorej su ovladane komponenty JPanel pri dokoncovani vytvarania
 * noveho projektu.
 */
public class ProjectSummary extends javax.swing.JPanel {

  
    private Project project;
    
    /**
     * Konstruktor, v ktorom sa inicializuju komponenty okna podla vytvaraneho
     * projektu.
     * @param project Projekt, ktory chceme vytvorit. Sluzi pre ziskanie detailov
     * projektu.
     */
    public ProjectSummary(Project project) {
        this.project = project;
        initComponents();
        if(project != null)
            loadData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        projectPriorityGroup = new javax.swing.ButtonGroup();
        taskDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taskList = new javax.swing.JList<>();
        lablDescription = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teamTable = new javax.swing.JTable();
        btnCreateProject = new javax.swing.JButton();
        btnTasksDetail = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();

        taskDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Project Tasks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        taskList.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        taskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        taskList.setMaximumSize(null);
        taskList.setPreferredSize(null);
        jScrollPane3.setViewportView(taskList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane3, gridBagConstraints);

        taskDialog.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Project > Teammates > Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.GridBagLayout());

        lablDescription.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lablDescription.setForeground(new java.awt.Color(0, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/bundle"); // NOI18N
        lablDescription.setText(bundle.getString("TEAM")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lablDescription, gridBagConstraints);

        lblName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText(bundle.getString("JLABEL2")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 5);
        add(lblName, gridBagConstraints);

        lblDescription.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(0, 0, 0));
        lblDescription.setText(bundle.getString("JLABEL3")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        add(lblDescription, gridBagConstraints);

        teamTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        teamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teamTable.setColumnSelectionAllowed(true);
        teamTable.setRowHeight(36);
        teamTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(teamTable);
        teamTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(jScrollPane1, gridBagConstraints);

        btnCreateProject.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnCreateProject.setText(bundle.getString("CREATE PROJECT")); // NOI18N
        btnCreateProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateProjectMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(btnCreateProject, gridBagConstraints);

        btnTasksDetail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnTasksDetail.setText(bundle.getString("PROJECT TASKS")); // NOI18N
        btnTasksDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTasksDetailMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(btnTasksDetail, gridBagConstraints);

        taskTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task", "Priority", "Deadline"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        taskTable.setRowHeight(36);
        taskTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(taskTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Funkcia sluzi pre zachytenie udalosti kliknutia na tlacidlo "vytvorit projekt"
     * a zabezpecuje priradenie projektu a uloh k pouzivatelom.
     * @param evt 
     */
    private void btnCreateProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateProjectMouseClicked
        
        Loader.addProject(project);
        SwingUtilities.getWindowAncestor(this).dispose();
        for (int i = 0; i < project.getTeams().size(); i++) {
            Team team = project.getTeams().get(i);
            for (User user : team.getTeamMembers()) {
                Loader.findUser(user.getUsername()).addProject(project);
            }
        }
        Loader.findUser(Loader.getCurrentlyLogged().getUsername()).addProject(project);
        
    }//GEN-LAST:event_btnCreateProjectMouseClicked

    /**
     * Otvori dialogove okno zobrazujuce ulohy (task) pridelene projektu.
     * @param evt 
     */
    private void btnTasksDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTasksDetailMouseClicked
        
        DefaultListModel<Task> listModel = new DefaultListModel<>();//(DefaultListModel)taskList.getModel();
        
        if(project.getTasks() != null){
            project.getTasks().forEach(taks -> {
                listModel.addElement(taks);
            });
        }
        
        taskList.setModel(listModel);
        taskDialog.setVisible(true);
    }//GEN-LAST:event_btnTasksDetailMouseClicked

    //UserCode 
    
    /**
     * Funkcia sluzi pre inicializovanie hodnot komponentov v okne.
     */
    private void loadData(){
        
        SimpleDateFormat formatter = new SimpleDateFormat(java.util.ResourceBundle.getBundle("sk/stu/fiit/bundle").getString("DD.MM.YYYY"));
        
        if(project != null){
            lblDescription.setText(project.getDescription());
            lblName.setText(project.getProjectName());

            DefaultTableModel teamModel = (DefaultTableModel) teamTable.getModel();

            project.getTeams().forEach(team ->{
                team.getTeamMembers().forEach(member -> {
                    teamModel.addRow(new Object[] {member.getName(), 
                        member.getUsername(), member.getType()  });
                });
            });
            
            DefaultTableModel taskModel = (DefaultTableModel) taskTable.getModel();
            
            project.getTasks().forEach(task ->{
            taskModel.addRow(new Object[]{task.getName(), task.getPriority().toString(),
                formatter.format(task.getDeadline())});
           });
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateProject;
    private javax.swing.JButton btnTasksDetail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lablDescription;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.ButtonGroup projectPriorityGroup;
    private javax.swing.JDialog taskDialog;
    private javax.swing.JList<Task> taskList;
    private javax.swing.JTable taskTable;
    private javax.swing.JTable teamTable;
    // End of variables declaration//GEN-END:variables
}
